apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-workflows      
    repoURL: http://argoproj.github.io/argo-helm
    targetRevision: 0.5.0
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
      - CreateNamespace=true